//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_ARWDA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARDWAEntities : DbContext
    {
        public ARDWAEntities()
            : base("name=ARDWAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssignPerson> AssignPersons { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<ErrorData> ErrorDatas { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MasterInstrument> MasterInstruments { get; set; }
        public virtual DbSet<Polling> Pollings { get; set; }
    }
}
