//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_ARWDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audit()
        {
            this.ErrorDatas = new HashSet<ErrorData>();
        }
    
        public string ProcesseedFileName { get; set; }
        public System.DateTime ProcessedDateTime { get; set; }
        public int RowsInFile { get; set; }
        public Nullable<int> AutoProcessedRows { get; set; }
        public Nullable<int> RowsUnknownStock { get; set; }
        public Nullable<int> RowsInvalidDate { get; set; }
        public Nullable<int> RowsMissingData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorData> ErrorDatas { get; set; }
    }
}
