//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_ARWDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorData
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string ErrorFieldColumn { get; set; }
        public Nullable<int> AnalystID { get; set; }
        public string AnalystComment { get; set; }
        public Nullable<System.DateTime> AnalystCompletedTime { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string ManagerComment { get; set; }
        public Nullable<System.DateTime> ManagerCompletedTime { get; set; }
        public int DividendID { get; set; }
        public string Symbol { get; set; }
        public string IssueName { get; set; }
        public string CUSIP { get; set; }
        public string IssueType { get; set; }
        public Nullable<int> OutstandingShares { get; set; }
        public string Frequency { get; set; }
        public System.DateTime ExDate { get; set; }
        public System.DateTime DeclaredDate { get; set; }
        public System.DateTime ConfirmationDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CAType { get; set; }
        public Nullable<decimal> DividendAmount { get; set; }
        public string DividendCurrency { get; set; }
        public Nullable<decimal> Distribution { get; set; }
        public Nullable<decimal> RatioTo { get; set; }
        public Nullable<decimal> RatioFor { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public string FinalAmountCurrency { get; set; }
        public string RemoveFlag { get; set; }
        public string CancellationReason { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string MiscNotes { get; set; }
        public string Market { get; set; }
        public string ForeignPrivateIssuerFlag { get; set; }
        public Nullable<decimal> NormalAmount { get; set; }
        public string LongTermCapitalGains { get; set; }
        public string ShortTermCapitalGains { get; set; }
        public string ReturnOfCapital { get; set; }
        public string Special { get; set; }
        public string Other { get; set; }
    
        public virtual Audit Audit { get; set; }
    }
}
