//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_ARWDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public int PersonLevel { get; set; }
        public string EmailAddress { get; set; }
        public string ForgotFlag { get; set; }
        public int AssignedOfficer { get; set; }
    
        public virtual AssignPerson AssignPerson { get; set; }
    }
}
